apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreg
  labels:
    app: myreg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myreg
  template:
    metadata:
      labels:
        app: myreg
    spec:
      containers:
      - name: registry
        image: registry
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: myreg
spec:
  selector:
    app: myreg
  ports:
    - protocol: TCP
      port: 5000
  type: NodePort

